# Generated by Django 5.0 on 2023-12-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obis', '0002_alter_lesson_lesson_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='lessons',
        ),
        migrations.AddField(
            model_name='student',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='obis.lesson'),
        ),
    ]
